### ISSUE TITLE
Add site language field to opt-in form as a hidden parameter

### ISSUE THREAD

**Issue by sinukaarel** [sendsmaily/smaily-opencart-module#100]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I add a contact to the Smaily from the site's opt-in form, but the contact doesn't have a language field that allows me to filter contacts.

**Describe the solution you'd like**
I would like to receive a `language` parameter that mirrors the current site language as a default parameter when customers sign up for the newsletter form.

**Describe alternatives you've considered**
Currently, a hidden field with site URL allows to filter out subscribers based on the site URL, but that's a hack to get the language parameter from the URL. More convenient would be to get the language field directly as it is the most common way to separate customers' emails that they receive.

**Comment by TomAbel** [comment]
this was fixed with 1.4.0 (1.2.0 for OC 1.5).
