### ISSUE TITLE
Abandoned cart CRON can get stuck

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-opencart-module#124]
**Bug description**
Customer, with an email address that Smaily does not recognize as valid, can cause abandoned cart CRON to get stuck trying to resubmit invalid data to Smaily API until an abandoned cart with a valid email address is added.

**Steps for reproducing**

As an admin:
1. Go to your stores admin panel;
2. Enable and connect module with Smaily;
3. Configure Abandoned Cart functionality and CRON job;

As a anonymous user:
1. Go to your store;
2. Register a customer with invalid email address (like customer@smaily.sandbox);
3. Login to registered customer's account;
4. Add products to your shopping cart;
5. Wait for the abandoned cart CRON to run;

**Expected behavior**
CRON discards invalid email address and does not try to resend invalid data to Smaily API until an abandoned cart with valid email address is added.

**Actual behavior**
CRON tries to resend abandoned cart request to Smaily API on every cycle until an abandoned cart with valid email address is added.

**Versions**
OpenCart: 3.0.3.1
Smaily For Opencart: 1.3.2

Since 1.4.0 did not make any changes to Abandoned Cart CRON or its helpers, then it is safe to assume that 1.4.0 does not fix it.

**Comment by kaittodesk** [comment]
Tested it only on 3.0.x branch, but it might be an issue with 2.2.x and 2.3.x branch also.

**Comment by TomAbel** [comment]
can confirm. 2.2.x and 2.3.x also affected

**Comment by TomAbel** [comment]
Fixed in 1.5.0.
