### ISSUE TITLE
Show module version under settings page in admin

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-opencart-module#125]
**Is your feature request related to a problem? Please describe.**
I might be getting old and my eyesight isn't what it used to be, or I am not very familiar with OpenCart, but I cannot find seem to find the version of the module anywhere in admin panel.

**Describe the solution you'd like**
It would be nice if the version of the module is shown somewhere on the module settings page.

**Versions**
OpenCart: 3.0.3.1

**Comment by TomAbel** [comment]
available in 1.5.0
