### ISSUE TITLE
Product description isn't displayed correctly

### ISSUE THREAD

**Issue by marispulk** [sendsmaily/smaily-opencart-module#168]
**Bug description**
RSS feed doesn't display product description correctly.

**Steps for reproducing**

1. Go to the RSS feed tab under Extensions → Modules.
2. Click on Smaily for OpenCart.
3. Copy RSS URL into your template editor's RSS block, to receive RSS feed.
4. You can see product description isn't displayed correctly neither on settings tab nor the template.

**Expected behavior**
Product description should appear correctly on both, settings tab and template, without any coding symbols being visible.

**Actual behavior**
Divs, paragraph tags and other coding symbols are displayed inside text.

**Screenshots**
Screenshot of RSS feed:
![RSS screen](https://i.imgur.com/UG7KCXf.png?1)

**OpenCart version**
Version 3.0.3.6

**Module version**
Version 1.4.0

**Additional context**
Needs testing also on OpenCart 1.5.x, 2.2.x, 2.3.x.

**Comment by TomAbel** [comment]
fixed in 1.5.1 for OpenCart 2.2.x, 2.3.x, 3.0.x
fixed in 1.3.1 for OpenCart 1.5.x
