### ISSUE TITLE
Error on execute cron

### ISSUE THREAD

**Issue by raphaelcordeiro** [sendsmaily/smaily-opencart-module#35]
When I try to execute customers syncronization, I've got this error:

Notice: Undefined property: Proxy::getSettingValue in /home2/starf675/saojosesports.com.br/system/storage/modification/system/engine/loader.php on line 161

Opencart 2.2.0.0

**Comment by sinukaarel** [comment]
This error message seems to be for opencart 2.3.+ version. Are you sure that you are using the correct version of our plugin?

Version 2.2 and version 2.3 have major changes, the 2.2 version plugin would not work for 2.3+ version of Opencart

**Comment by raphaelcordeiro** [comment]
Yes. I've downloaded the correct version from your github.

**Comment by kaittodesk** [comment]
Hm. There is something to it. With fresh OpenCart 2.2.0.0 installation in the development environment I get a similar error:

> Notice: Undefined property: Proxy::getSettingValue in /path/to/catalog/model/smailyforopencart/helper.php on line 213

**Comment by sinukaarel** [comment]
I have looked into it and the `getSettingValue()` function seems to be wrong.
https://github.com/sendsmaily/smaily-opencart-module/blob/413b3b0a2402898192087f4e02b8c4d9cc527bb6/opencart%202.2.0.0/upload/catalog/model/smailyforopencart/helper.php#L213

The correct function is `getSetting()`. 

@raphaelcordeiro So for a quick fix you can change the function `getSettingValue()` to `getSetting()`  in `catalog/model/smailyforopencart/helper.php` on line 213 - until we make an official hotfix.

**Comment by sinukaarel** [comment]
We have now released fixed version https://github.com/sendsmaily/smaily-opencart-module/releases/tag/2.2.x-1.2.1
@raphaelcordeiro you can also try out the `smailyforopencart-2.2.x-1.2.1.ocmod.zip` in the release assets. I recommend uninstalling the previous version and installing the new one with using OpenCart extension installer.

**Comment by sinukaarel** [comment]
Fixed in #46
