### ISSUE TITLE
Module does not get enabled after successful API credentials validation

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-opencart-module#49]
Module should be automatically enabled on successful API credentials validation, even if user explicitly selects "Enable" from the dropdown.

Had this issue with `2.2.x` branch, but this might be an issue with all of the newer versions as well.

**Comment by sinukaarel** [comment]
Fixed with #59 for branch 2.3.x and #60 for branch 2.2.x

**Comment by sinukaarel** [comment]
Opening for branch 3.0.x

**Comment by sinukaarel** [comment]
Fixed with #63
