### ISSUE TITLE
Abandoned cart emails doesn't works OC 2.2.0.0

### ISSUE THREAD

**Issue by raphaelcordeiro** [sendsmaily/smaily-opencart-module#50]
Smaily get normally all the informations about abandoned carts, but doesn't send e-mails about abandoned carts.

**Comment by kaittodesk** [comment]
@raphaelcordeiro thank you for reporting the issue, testing the plugin and sticking with us :)

I think this might be related to #36 - if the autoresponder ID is not properly added to the abandoned cart API request, the automation will not be triggered.

**Comment by raphaelcordeiro** [comment]
I've tried to put the id of automation manually in code, but it don't works too.

**Comment by raphaelcordeiro** [comment]
Now, autoresponders sync is ok, but abandoned carts mails are still not delivered.

**Comment by kaittodesk** [comment]
We did some more digging, and may have discovered an issue with collecting abandoned carts.

The module has a separate database table to track if abandoned cart email has already been sent to customer to avoid bombarding customer with abandoned cart emails every time CRON runs. This tracker gets reset only when customer completes their order, but not when customer adds products to cart or removes them.

@raphaelcordeiro, can you try and remove a row for a specific customer from `oc_smaily_abandoned_cart` table and see if abandoned cart email gets sent out then?

**Comment by TomAbel** [comment]
This should be solved by #73, if the problem persists, please let us know by leaving a comment.
