### ISSUE TITLE
Customer sync fields not unified with abandoned cart fields

### ISSUE THREAD

**Issue by sinukaarel** [sendsmaily/smaily-opencart-module#54]
**Description**

The current customer sync fields for `first_name` and `last_name` are not unified with abandoned cart sync fields.

**Steps**
Run customer cron with `First name` and `Last name` additional fields. 

**Result**
Subscriber is added with `firstname` and `lastname` extra fields.

**Expected**
Customer cron sends newsletter subscriber with fields `first_name` and `last_name`.

**Comment by TomAbel** [comment]
merged into 1.4.0
closing this
