### ISSUE TITLE
Abandoned cart reminder is sent to very old carts

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-opencart-module#72]
When abandoned cart functionality is enabled in an existing store (the most likely scenario) it sends reminders to all carts that have not been checked out, including very old carts. This should not happen.

I propose we register date and time of abandoned cart functionality activation, and only include carts that have been created after that time. Registered date and time should update on each enable.

### Issue completed in branches:
- [x] OpenCart 2.2.x
- [x] OpenCart 2.3.x
- [x] OpenCart 3.3.x

**Comment by sinukaarel** [comment]
### Issue completed in branches:
- [ ] OpenCart 2.2.x
- [ ] OpenCart 2.3.x
- [ ] OpenCart 3.3.x

**Comment by sinukaarel** [comment]
Closing all branches fixed
